name: Tokens
version: '1.0-SNAPSHOT'
main: com.twanluttik.tokens.Tokens
api-version: '1.21'

softdepend:
  - DecentHolograms

commands:
  tokens:
    usage: /<command>
    description: main command

permissions:
  tokens.admin:
    description: Allows access to admin token commands
    default: op
  tokens.hologram:
    description: Allows access to hologram commands
    default: op