#
#
#                     <--- Tokens --->
#          Created by Twan Luttik, Config version 1.0
#

update_message: true
bonus_message: '&7you received {tokens} Tokens from your boss'


tokens:
  buy_price: 100
  sell_price: 100