name: Tokens
version: '${version}'
main: com.twanluttik.tokens.Tokens
api-version: 1.19
softdepend: ["PlaceholderAPI", "DecentHolograms"]

commands:
  tokens:
    usage: /<command>
    description: Main tokens command

permissions:
  tokens.admin:
    description: Grants access to admin token commands (give, take, set, hologram, bank management)
    default: op